require:
  # - rubocop-rails
  - rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'db/**/*'
    - 'bin/*'
  NewCops: enable

Layout/ClassStructure:
  Enabled: true

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineAssignmentLayout:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/LineLength:
  Enabled: 200

Metrics/BlockLength:
  Enabled: 60

Metrics/MethodLength:
  Enabled: 30

Metrics/AbcSize:
  Enabled: 40

Style/Documentation:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/NestedGroups:
  Max: 10

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - production
    - staging
